[workspace]
members = ["teensy-audio", "examples"]
resolver = "2"

[profile.release]
debug = 2
opt-level = "s"

[patch.crates-io]
imxrt-ral = { path = "../imxrt-ral" }
imxrt-iomuxc = { git = "https://github.com/imxrt-rs/imxrt-iomuxc" }
